### ISSUE TITLE
You'd better add Unit test to test the framework

### ISSUE THREAD

**Issue by MarcSteven** [marty-suzuki/FluxCapacitor#1]
Lack of the reasonable test ,you should add it to test the framework..Looking forward to extend its feature .

**Comment by marty-suzuki** [comment]
Hi, @MarcSteven 
Thank you for issuing!
I've added some tests in [FluxCapacitorTests](https://github.com/marty-suzuki/FluxCapacitor/tree/master/FluxCapacitorTests) directory.
